### ISSUE TITLE
[1.16.5] Server crash

### ISSUE THREAD

**Issue by j4p4n4s4** [FatherToast/SpecialMobs#22]
[02oct2022 18:26:19.085] [Server thread/FATAL] [net.minecraftforge.common.ForgeMod/]: Preparing crash report with UUID 1edb7d89-33a0-4144-a01c-71cf724393ae
[02oct2022 18:26:19.096] [Server thread/ERROR] [net.minecraft.server.MinecraftServer/]: Encountered an unexpected exception
net.minecraft.crash.ReportedException: Ticking entity
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:855) ~[?:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:291) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) ~[?:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_341]
Caused by: java.util.ConcurrentModificationException
	at java.util.LinkedHashMap$LinkedHashIterator.nextNode(Unknown Source) ~[?:1.8.0_341]
	at java.util.LinkedHashMap$LinkedKeyIterator.next(Unknown Source) ~[?:1.8.0_341]
	at java.util.Iterator.forEachRemaining(Unknown Source) ~[?:1.8.0_341]
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Unknown Source) ~[?:1.8.0_341]
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:1.8.0_341]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:1.8.0_341]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source) ~[?:1.8.0_341]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source) ~[?:1.8.0_341]
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:1.8.0_341]
	at java.util.stream.ReferencePipeline.forEach(Unknown Source) ~[?:1.8.0_341]
	at net.minecraft.entity.ai.goal.GoalSelector.func_75774_a(SourceFile:88) ~[?:?]
	at net.minecraft.entity.MobEntity.func_70626_be(MobEntity.java:682) ~[?:?]
	at net.minecraft.entity.LivingEntity.func_70636_d(LivingEntity.java:2413) ~[?:?]
	at net.minecraft.entity.MobEntity.func_70636_d(MobEntity.java:488) ~[?:?]
	at net.minecraft.entity.monster.MonsterEntity.func_70636_d(SourceFile:43) ~[?:?]
	at net.minecraft.entity.monster.ZombieEntity.func_70636_d(ZombieEntity.java:231) ~[?:?]
	**at fathertoast.specialmobs.common.entity.zombie._SpecialZombieEntity.func_70636_d(_SpecialZombieEntity.java:306) ~[specialmobs:1.16.5-1.0.1]**
	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2160) ~[?:?]
	at net.minecraft.entity.MobEntity.func_70071_h_(MobEntity.java:300) ~[?:?]
	at net.minecraft.entity.monster.ZombieEntity.func_70071_h_(ZombieEntity.java:205) ~[?:?]
	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:612) ~[?:?]
	at net.minecraft.world.World.func_217390_a(World.java:554) ~[?:?]
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:405) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:851) ~[?:?]
	... 5 more
[02oct2022 18:26:19.173] [Server thread/ERROR] [net.minecraft.server.MinecraftServer/]: This crash report has been saved to: D:\Servidores\Minecraft\Minecraft_1165_LAST FORGE\.\crash-reports\crash-2022-10-02_18.26.19-server.txt
[02oct2022 18:26:19.185] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Stopping server
[02oct2022 18:26:19.245] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving players
[02oct2022 18:26:19.329] [Server thread/INFO] [net.minecraft.network.play.ServerPlayNetHandler/]: j4p4n4s4 lost connection: Internal Exception: java.lang.StackOverflowError
[02oct2022 18:26:19.396] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer/]: j4p4n4s4 left the game
[02oct2022 18:26:19.460] [Server thread/ERROR] [net.minecraft.server.MinecraftServer/]: Exception stopping the server
java.lang.IllegalStateException: Removing entity while ticking!
	at net.minecraft.world.server.ServerWorld.removeEntity(ServerWorld.java:950) ~[?:?]
	at net.minecraft.world.server.ServerWorld.removePlayer(ServerWorld.java:971) ~[?:?]
	at net.minecraft.world.server.ServerWorld.func_217434_e(ServerWorld.java:967) ~[?:?]
	at net.minecraft.server.management.PlayerList.func_72367_e(PlayerList.java:339) ~[?:?]
	at net.minecraft.network.play.ServerPlayNetHandler.func_147231_a(ServerPlayNetHandler.java:1021) ~[?:?]
	at net.minecraft.network.NetworkManager.func_179293_l(NetworkManager.java:366) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213167_f(SourceFile:79) ~[?:?]
	at net.minecraft.network.play.ServerPlayNetHandler.func_194028_b(ServerPlayNetHandler.java:296) ~[?:?]
	at net.minecraft.server.management.PlayerList.func_72392_r(PlayerList.java:742) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71260_j(MinecraftServer.java:557) ~[?:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71260_j(DedicatedServer.java:514) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:679) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) ~[?:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_341]

[crash-2022-10-02_18.26.19-server.txt](https://github.com/FatherToast/SpecialMobs/files/9693001/crash-2022-10-02_18.26.19-server.txt)

**Comment by FatherToast** [comment]
Can you provide some context as to what caused this?  Since this is a comod exception, the cause could be literally anything - all I can tell is that something caused the zombie's AI to be changed within its own AI loop.  Most likely something that changed its held item.

**Comment by j4p4n4s4** [comment]
It has been random. But I had problems in that area when playing in singleplayer after adding this mod. (new chunks were not generated and entities were not updated).

Mods that modify the AI ​​only this Special AI. Majruzzs difficulty I also have it but I think it only modifies attributes and spawn values.

The server has started perfectly and I have been able to continue the game for quite some time without problems in that same area.

**Comment by FatherToast** [comment]
Hm, I'll keep this in mind, but not sure if there's anything I can do until I figure out what is causing the issue.  This is more likely an issue with Special AI than Special Mobs, but hard to tell, and could be neither of them.  If it happens again, please post the crash log in this same thread, maybe it will help narrow down the cause.

**Comment by Sarinsa** [comment]
No longer maintaining 1.16.5
