### ISSUE TITLE
I get this error and logged out from the server

### ISSUE THREAD

**Issue by Dream-Master** [FatherToast/SpecialMobs#4]
Pack i play:

https://github.com/GTNewHorizons/NewHorizons

Lastest Special mobs. 3.2.2

```
[B#347] 2016/09/29 15:47:57 [INFO]  [15:47:57] [Client thread/ERROR] [FML]: SimpleChannelHandlerWrapper exception
[B#347] 2016/09/29 15:47:57 [INFO]  java.lang.OutOfMemoryError: Java heap space
[B#347] 2016/09/29 15:47:57 [INFO]      at toast.specialMobs.network.MessageExplosion.fromBytes(MessageExplosion.java:118) ~[MessageExplosion.class:?]
[B#347] 2016/09/29 15:47:57 [INFO]      at cpw.mods.fml.common.network.simpleimpl.SimpleIndexedCodec.decodeInto(SimpleIndexedCodec.java:17) ~[SimpleIndexedCodec.class:?]
[B#347] 2016/09/29 15:47:57 [INFO]      at cpw.mods.fml.common.network.simpleimpl.SimpleIndexedCodec.decodeInto(SimpleIndexedCodec.java:7) ~[SimpleIndexedCodec.class:?]
[B#347] 2016/09/29 15:47:57 [INFO]      at cpw.mods.fml.common.network.FMLIndexedMessageToMessageCodec.decode(FMLIndexedMessageToMessageCodec.java:77) ~[FMLIndexedMessageToMessageCodec.class:?]
[B#347] 2016/09/29 15:47:57 [INFO]      at cpw.mods.fml.common.network.FMLIndexedMessageToMessageCodec.decode(FMLIndexedMessageToMessageCodec.java:17) ~[FMLIndexedMessageToMessageCodec.class:?]
[B#347] 2016/09/29 15:47:57 [INFO]      at io.netty.handler.codec.MessageToMessageCodec$2.decode(MessageToMessageCodec.java:81) ~[MessageToMessageCodec$2.class:?]
[B#347] 2016/09/29 15:47:57 [INFO]      at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:89) ~[MessageToMessageDecoder.class:?]
[B#347] 2016/09/29 15:47:57 [INFO]      at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) ~[MessageToMessageCodec.class:?]
[B#347] 2016/09/29 15:47:57 [INFO]      at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
[B#347] 2016/09/29 15:47:57 [INFO]      at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
[B#347] 2016/09/29 15:47:57 [INFO]      at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) [DefaultChannelPipeline.class:?]
[B#347] 2016/09/29 15:47:57 [INFO]      at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) [EmbeddedChannel.class:?]
[B#347] 2016/09/29 15:47:57 [INFO]      at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [FMLProxyPacket.class:?]
[B#347] 2016/09/29 15:47:57 [INFO]      at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
[B#347] 2016/09/29 15:47:57 [INFO]      at net.minecraft.client.multiplayer.PlayerControllerMP.func_78765_e(Unknown Source) [bje.class:?]
[B#347] 2016/09/29 15:47:57 [INFO]      at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1602) [bao.class:?]
[B#347] 2016/09/29 15:47:57 [INFO]      at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973) [bao.class:?]
[B#347] 2016/09/29 15:47:57 [INFO]      at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898) [bao.class:?]
[B#347] 2016/09/29 15:47:57 [INFO]      at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
[B#347] 2016/09/29 15:47:57 [INFO]      at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_60]
[B#347] 2016/09/29 15:47:57 [INFO]      at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_60]
[B#347] 2016/09/29 15:47:57 [INFO]      at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_60]
[B#347] 2016/09/29 15:47:57 [INFO]      at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_60]
[B#347] 2016/09/29 15:47:57 [INFO]      at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
[B#347] 2016/09/29 15:47:57 [INFO]      at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
[B#347] 2016/09/29 15:47:57 [INFO]  [15:47:57] [Client thread/ERROR] [FML]: SimpleChannelHandlerWrapper exception
```

**Comment by Drobac** [comment]
This caused everyone on the overworld to get kicked off the server, no other dimensions were affected. Repeated every 20ish minutes when the server population was higher

**Comment by Sarinsa** [comment]
Likely resolved. Vanilla explosion FX packet is being sent instead now
