### ISSUE TITLE
Crash due to using Potion.isBadEffect on server side

### ISSUE THREAD

**Issue by Corosauce** [FatherToast/SpecialMobs#5]
Using SpecialMobs-1.7.10-3.2.2.jar, problem method is marked SideOnly(Side.CLIENT) so it crashes for serverside use.

The sideonly marking was at least removed in 1.10.2 so it wont be an issue in future.

Can be fixed by ATing the similarly named Potion.isBadEffect to make it not final and public then just reference field instead of badly annotated method.

Issue still exists in plain forge 1614 for 1.7.10 so not using cauldron or updating to latest forge wont fix it.

java.lang.NoSuchMethodError: net.minecraft.potion.Potion.func_76398_f()Z
        at toast.specialMobs.entity.witch.EntityDominationWitch.onTypeAttack(EntityDominationWitch.java:96) ~[EntityDominationWitch.class:?]
        at toast.specialMobs.entity.witch.Entity_SpecialWitch.func_70652_k(Entity_SpecialWitch.java:268) ~[Entity_SpecialWitch.class:?]
        at net.minecraft.entity.ai.EntityAIAttackOnCollide.func_75246_d(EntityAIAttackOnCollide.java:162) ~[uq.class:?]
        at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:103) ~[uj.class:?]
        at net.minecraft.entity.EntityLiving.func_70619_bc(EntityLiving.java:582) ~[sw.class:?]
        at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2066) ~[sv.class:?]
        at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:388) ~[sw.class:?]
        at net.minecraft.entity.monster.EntityMob.func_70636_d(EntityMob.java:36) ~[yg.class:?]
        at net.minecraft.entity.monster.EntityWitch.func_70636_d(SourceFile:140) ~[yp.class:?]
        at toast.specialMobs.entity.witch.Entity_SpecialWitch.func_70636_d(Entity_SpecialWitch.java:199) ~[Entity_SpecialWitch.class:?]
        at toast.specialMobs.entity.witch.EntityDominationWitch.func_70636_d(EntityDominationWitch.java:84) ~[EntityDominationWitch.class:?]
        at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1899) ~[sv.class:?]
        at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:213) ~[sw.class:?]
        at net.minecraft.entity.monster.EntityMob.func_70071_h_(EntityMob.java:41) ~[yg.class:?]
        at net.minecraft.world.World.func_72866_a(World.java:2674) ~[ahb.class:?]
        at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:800) ~[mt.class:?]
        at net.minecraft.world.World.func_72870_g(World.java:2623) ~[ahb.class:?]
        at net.minecraft.world.World.func_72939_s(World.java:2423) ~[ahb.class:?]
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:633) ~[mt.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:954) ~[MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431) ~[lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:809) ~[MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]

**Comment by Sarinsa** [comment]
Fixing for upcoming release

**Comment by Sarinsa** [comment]
Fixed!
